//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryID;CategoryName;Description
        ///1;Beverages;Soft drinks, coffees, teas, beers, and ales
        ///2;Condiments;Sweet and savory sauces, relishes, spreads, and seasonings
        ///3;Confections;Desserts, candies, and sweet breads
        ///4;Dairy Products;Cheeses
        ///5;Grains/Cereals;Breads, crackers, pasta, and cereal
        ///6;Meat/Poultry;Prepared meats
        ///7;Produce;Dried fruit and bean curd
        ///8;Seafood;Seaweed and fish
        ///.
        /// </summary>
        internal static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerID;CustomerTypeID
        ///.
        /// </summary>
        internal static string customer_customer_demo {
            get {
                return ResourceManager.GetString("customer_customer_demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerTypeID;CustomerDesc
        ///.
        /// </summary>
        internal static string customer_demographics {
            get {
                return ResourceManager.GetString("customer_demographics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerID;CompanyName;ContactName;ContactTitle;Address;City;Region;PostalCode;Country;Phone;Fax
        ///ALFKI;Alfreds Futterkiste;Maria Anders;Sales Representative;Obere Str. 57;Berlin;;12209;Germany;030-0074321;030-0076545
        ///ANATR;Ana Trujillo Emparedados y helados;Ana Trujillo;Owner;Avda. de la Constituci¢n 2222;M‚xico D.F.;;05021;Mexico;(5) 555-4729;(5) 555-3745
        ///ANTON;Antonio Moreno Taquer¡a;Antonio Moreno;Owner;Mataderos  2312;M‚xico D.F.;;05023;Mexico;(5) 555-3932;
        ///AROUT;Around the Horn;Thomas Hardy;Sales R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string customers {
            get {
                return ResourceManager.GetString("customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeID;TerritoryID
        ///1;6897
        ///1;19713
        ///2;1581
        ///2;1730
        ///2;1833
        ///2;2116
        ///2;2139
        ///2;2184
        ///2;40222
        ///3;30346
        ///3;31406
        ///3;32859
        ///3;33607
        ///4;20852
        ///4;27403
        ///4;27511
        ///5;2903
        ///5;7960
        ///5;8837
        ///5;10019
        ///5;10038
        ///5;11747
        ///5;14450
        ///6;85014
        ///6;85251
        ///6;98004
        ///6;98052
        ///6;98104
        ///7;60179
        ///7;60601
        ///7;80202
        ///7;80909
        ///7;90405
        ///7;94025
        ///7;94105
        ///7;95008
        ///7;95054
        ///7;95060
        ///8;19428
        ///8;44122
        ///8;45839
        ///8;53404
        ///9;3049
        ///9;3801
        ///9;48075
        ///9;48084
        ///9;48304
        ///9;55113
        ///9;55439
        ///.
        /// </summary>
        internal static string employee_territories {
            get {
                return ResourceManager.GetString("employee_territories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeID;LastName;FirstName;Title;TitleOfCourtesy;BirthDate;HireDate;Address;City;Region;PostalCode;Country;HomePhone;Extension;Notes;ReportsTo
        ///1;Davolio;Nancy;Sales Representative;Ms.;1948-12-08 00:00:00.000;1992-05-01 00:00:00.000;507 - 20th Ave. E. Apt. 2A;Seattle;WA;98122;USA;(206) 555-9857;5467;&quot;Education includes a BA in psychology from Colorado State University in 1970.  She also completed &quot;&quot;The Art of the Cold Call.&quot;&quot;  Nancy is a member of Toastmasters International.&quot;;2
        ///2;Fuller;Andrew;Vice Pres [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string employees {
            get {
                return ResourceManager.GetString("employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderID;ProductID;UnitPrice;Quantity;Discount
        ///10248;11;14;12;0
        ///10248;42;9.8;10;0
        ///10248;72;34.8;5;0
        ///10249;14;18.6;9;0
        ///10249;51;42.4;40;0
        ///10250;41;7.7;10;0
        ///10250;51;42.4;35;0.15000001
        ///10250;65;16.8;15;0.15000001
        ///10251;22;16.8;6;5.0000001E-2
        ///10251;57;15.6;15;5.0000001E-2
        ///10251;65;16.8;20;0
        ///10252;20;64.8;40;5.0000001E-2
        ///10252;33;2;25;5.0000001E-2
        ///10252;60;27.2;40;0
        ///10253;31;10;20;0
        ///10253;39;14.4;42;0
        ///10253;49;16;40;0
        ///10254;24;3.6;15;0.15000001
        ///10254;55;19.2;21;0.15000001
        ///10254;74;8;21;0
        ///102 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string order_details {
            get {
                return ResourceManager.GetString("order_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderID;CustomerID;EmployeeID;OrderDate;RequiredDate;ShippedDate;ShipVia;Freight;ShipName;ShipAddress;ShipCity;ShipRegion;ShipPostalCode;ShipCountry
        ///10248;VINET;5;1996-07-04 00:00:00;1996-08-01 00:00:00;1996-07-16 00:00:00;3;32.38;Vins et alcools Chevalier;59 rue de l&apos;Abbaye;Reims;;51100;France
        ///10249;TOMSP;6;1996-07-05 00:00:00;1996-08-16 00:00:00;1996-07-10 00:00:00;1;11.61;Toms Spezialit„ten;Luisenstr. 48;Mnster;;44087;Germany
        ///10250;HANAR;4;1996-07-08 00:00:00;1996-08-05 00:00:00;1996-07-12 00:00:00;2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string orders {
            get {
                return ResourceManager.GetString("orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductID;ProductName;SupplierID;CategoryID;QuantityPerUnit;UnitPrice;UnitsInStock;UnitsOnOrder;ReorderLevel;Discontinued
        ///1;Chai;1;1;10 boxes x 20 bags;18;39;0;10;0
        ///2;Chang;1;1;24 - 12 oz bottles;19;17;40;25;0
        ///3;Aniseed Syrup;1;2;12 - 550 ml bottles;10;13;70;25;0
        ///4;Chef Anton&apos;s Cajun Seasoning;2;2;48 - 6 oz jars;22;53;0;0;0
        ///5;Chef Anton&apos;s Gumbo Mix;2;2;36 boxes;21.35;0;0;0;-1
        ///6;Grandma&apos;s Boysenberry Spread;3;2;12 - 8 oz jars;25;120;0;25;0
        ///7;Uncle Bob&apos;s Organic Dried Pears;3;7;12 - 1 lb pkgs.;30;15;0; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegionID;RegionDescription
        ///1;Eastern                                           
        ///2;Western                                           
        ///3;Northern                                          
        ///4;Southern                                          .
        /// </summary>
        internal static string region {
            get {
                return ResourceManager.GetString("region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipperID;CompanyName;Phone
        ///1;Speedy Express;(503) 555-9831
        ///2;United Package;(503) 555-3199
        ///3;Federal Shipping;(503) 555-9931
        ///.
        /// </summary>
        internal static string shippers {
            get {
                return ResourceManager.GetString("shippers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierID;CompanyName;ContactName;ContactTitle;Address;City;Region;PostalCode;Country;Phone;Fax;HomePage
        ///1;Exotic Liquids;Charlotte Cooper;Purchasing Manager;49 Gilbert St.;London;NULL;EC1 4SD;UK;(171) 555-2222;NULL;NULL
        ///2;New Orleans Cajun Delights;Shelley Burke;Order Administrator;P.O. Box 78934;New Orleans;LA;70117;USA;(100) 555-4822;NULL;#CAJUN.HTM#
        ///3;Grandma Kelly&apos;s Homestead;Regina Murphy;Sales Representative;707 Oxford Rd.;Ann Arbor;MI;48104;USA;(313) 555-5735;(313) 555-3349;NULL
        ///4;Tokyo Traders [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string suppliers {
            get {
                return ResourceManager.GetString("suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TerritoryID;TerritoryDescription;RegionID
        ///01581;Westboro;1
        ///01730;Bedford;1
        ///01833;Georgetow;1
        ///02116;Boston;1
        ///02139;Cambridge;1
        ///02184;Braintree;1
        ///02903;Providence;1
        ///03049;Hollis;3
        ///03801;Portsmouth;3
        ///06897;Wilton;1
        ///07960;Morristown;1
        ///08837;Edison;1
        ///10019;New York;1
        ///10038;New York;1
        ///11747;Mellvile;1
        ///14450;Fairport;1
        ///19428;Philadelphia;3
        ///19713;Neward;1
        ///20852;Rockville;1
        ///27403;Greensboro;1
        ///27511;Cary;1
        ///29202;Columbia;4
        ///30346;Atlanta;4
        ///31406;Savannah;4
        ///32859;Orlando;4
        ///33607;Tampa;4
        ///40222 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string territories {
            get {
                return ResourceManager.GetString("territories", resourceCulture);
            }
        }
    }
}
